name: Deploy to staging

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run tests
        run: mvn --batch-mode clean test
      - name: Build
        env:
          TOKEN: ${{secrets.DISCORD_TOKEN}}
        run: echo "discord.bot.token=\"$TOKEN\"" > src/main/resources/sensitive.conf
      - name: Deploy to heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: mvn --batch-mode heroku:deploy -Dmaven.test.skip=true -Dheroku.appName=lucius-gate
